// ========== UI 文案集中管理 ==========
export const UI = {
    // ----- 全局通用 -----
    common: {
        siteTitle: 'REVACHO',
        siteSubtitle: '· 原创角色档案馆 ·',
        appName: 'REVACHOL',
        loading: '加载中...',
        close: '关闭',
        cancel: '取消',
        save: '保存',
        confirm: '确认',
        delete: '删除',
        edit: '编辑',
        back: '返回',
        more: '更多',
        searchPlaceholder: '🔍 找点什么？',
        noResults: '无',
        unknown: '未知',
        searchResultCount: (count) => `找到 ${count} 个结果`,
        searchResultItem: (index, total, title) => `结果 ${index}/${total}: ${title}`,
        toggleVisible: '切换可见性',
    },

    // ----- 登录 -----
    login: {
        triggerLabel: '登录',
        welcomeText: '欢迎访客',
        adminLabel: '管理员',
        adminWelcome: '欢迎管理员',
        modalTitle: '🔐 管理员登录',
        usernameLabel: '用户名',
        passwordLabel: '密码',
        loginButton: '登录',
        hint: '普通用户无需登录',
        placeholderUsername: '请输入用户名',
        placeholderPassword: '请输入密码',
        errorEmpty: '用户名和密码不能为空',
        errorInvalid: '用户名或密码错误',
    },

    // ----- 管理员面板 -----
    admin: {
        panelTitle: '⚙️ 管理',
        collapseIcon: '▶',
        expandIcon: '▼',
        avatarUploadLabel: '📷 上传头像',
        avatarHint: '点击上传，可裁剪为正方形',
        textureUploadLabel: '🖼️ 纹理贴图',
        textureApplyButton: '应用纹理',
        textureRemoveButton: '移除纹理',
        textureOpacityLabel: '🎨 纹理透明度',
        watermarkTextLabel: '📝 水印文字',
        watermarkOpacityLabel: '🎨 水印透明度',
        watermarkApplyButton: '应用水印设置',
        videoOpacityLabel: '🎥 视频最大透明度',
        videoOpacityHint: '控制视频在页面顶部的最亮程度（0=完全透明，1=最亮）',
        bgModeLabel: '🎨 背景模式',
        bgModeSolid: '纯色',
        bgModeGradient: '渐变',
        gradientColorLabel: '🌈 颜色选择',
        gradientColorHint: '选择2~3种颜色，渐变将从上到下过渡',
        gradientDirectionLabel: '↕ 方向',
        gradientFeatherLabel: '🪶 羽化值',
        gradientFeatherHint: '数值越大，颜色过渡越柔和',
        gradientApplyButton: '✅ 应用渐变',
        paletteSaveButton: '💾 存入色卡',
        paletteNamePlaceholder: '色卡名称（可选）',
        paletteListLabel: '📚 色卡库',
        paletteEmpty: '暂无色卡',
        paletteApply: '应用色卡',
        paletteDelete: '删除色卡',
        decoLibraryLabel: '🖼️ 贴图库管理',
        decoUploadButton: '📤 上传贴图',
        decoUploadHint: '支持 PNG, WebP, JPG 格式（自动压缩为 WebP）',
        decoLoading: '加载中...',
        decoEmpty: '📭 暂无贴图',
        decoEmptyHint: '点击上方 "📤 上传贴图" 添加',
        decoItemPlaced: '📍已放置',
        decoItemUnplaced: '📦未放置',
        decoStyleLabel: '切换样式',
        decoStyleFixed: '悬浮',
        decoStyleAbsolute: '贴纸',
        decoDuplicate: '复制贴图',
        decoRename: '重命名',
        decoEditPos: '编辑位置',
        decoDownload: '下载贴图',
        decoDelete: '从库中删除',
        confirmPosButton: '✅ 确认位置',
        cancelPosButton: '❌ 取消编辑',
        articleEditorLabel: '📝 文章管理',
        articleEditorButton: '📝 进入文章编辑器',
        articleEditorHint: '在编辑器中管理文章和分类',
        articleVisibilityLabel: '📄 文章可见性控制',
        articleVisibilityHint: '请使用左侧 <strong>📜 目录树</strong> 中每篇文章旁的 <span style="color: #3a5a2b;">👁️</span> / <span style="color: #5a3e2b;">🚫</span> 按钮进行可见性切换。',
        articleVisibilityHintAdmin: '管理员登录后，在目录树中每个文章节点右侧会出现可见性控制按钮。',
        logoutButton: '退出登录',
        articleEmpty: '暂无文章，点击 “新建文章” 创建',
        positionModeEnter: '📌 进入位置管理',
        positionModeSave: '💾 保存更改',
        positionModeCancel: '❌ 取消',
        positionModeHint: '拖拽文章或文件夹调整位置，保存后生效',
    },

    // ----- 目录树 -----
    directory: {
        emptyTree: '空无一人',
        emptyFolder: '空文件夹',
        loading: '加载中...',
        folderIconCollapsed: '📂',
        folderIconExpanded: '📁',
        articleIcon: '📄',
        toggleVisible: '展开',
        toggleHidden: '折叠',
        menuEditArticle: '✏️ 编辑内容',
        menuRenameArticle: '🔄 重命名',
        menuNewArticle: '📄 新建文章',
        menuNewFolder: '📁 新建子文件夹',
        menuNewRootFolder: '📁 新建根文件夹',
        menuDeleteArticle: '❌ 删除文章',
        menuRenameFolder: '📝 重命名文件夹',
        menuDeleteFolderOnly: '🗑️ 删除文件夹（仅文件夹）',
        menuDeleteFolderWithArticles: '🗑️ 删除文件夹及文章',
        menuNewArticleRoot: '📄 新建文章',
        menuNewFolderRoot: '📁 新建根文件夹',
        folderNoArticles: (name) => `📁 "${name}" 文件夹暂无文章`,
        dragDropHint: '📥 拖拽到此空白区域 → 移动到平级位置',
    },

    // ----- 文章卡片与列表 -----
    articles: {
        empty: '⚡ 意识流空转 ⚡<br><small>尚未记录任何角色</small>',
        cardHint: '双击查看详情',
        cardMetaPrefix: '✍️ 最后修改 · ',
        loadMore: '📖 加载更多角色...',
        endMessage: '✨ 已经到底了 ✨',
        bottomToastEnd: '✨ 已经到底了 ✨',
        defaultCategory: '未分类档案',
        defaultTitle: '无名者',
        defaultContent: '无描述',
        unknownTime: '未知纪元',
        loading: '⏳ 正在加载角色...',
    },

    // ----- 详情页 -----
    detail: {
        tabClose: '✕',
        paneMinimize: '➖',
        paneFullscreen: '⛶',
        paneFullscreenExit: '⤢',
        paneClose: '✕',
        minimizeTitle: '最小化到左下角',
        minimizeToast: '已最小化到页面顶部',
        restoreFromMinimize: '↩',
        fullscreenTitle: '全屏/窗口切换',
        closeAllConfirm: '关闭所有标签页？',
        invisibleToast: '该文章已被设为不可见（管理员可继续阅读）',
        invisibleConfirm: '该文章已被管理员设置为不可见，点击确定关闭当前阅读窗口。',
        defaultTitle: '无标题',
        defaultContent: '无内容',
    },

    // ----- 贴纸 -----
    deco: {
        menuDuplicate: '📋 复制',
        menuPaste: '📋 粘贴',
        menuRename: '✏️ 重命名',
        menuEditPos: '📍 编辑位置',
        menuToggleStyle: '🔄 切换样式',
        menuRemovePage: '❌ 从网页删除',
        menuDeleteLib: '🗑️ 从库中删除',
        toggleStyleLabel: (style) => `🔄 切换为${style === 'fixed' ? '贴纸' : '悬浮窗'}`,
        pasteDisabled: '剪贴板为空',
        renamePrompt: '输入新名称：',
        deleteConfirm: (name) => `确定要从贴图库中删除 "${name}" 吗？`,
        duplicateSuccess: (name) => `已复制贴图 "${name}"`,
        deleteSuccess: (name) => `已删除 "${name}"`,
        editPosToast: '拖动贴图调整位置，点击"确认位置"保存',
        styleSwitched: (style) => `已切换为${style === 'fixed' ? '悬浮窗' : '贴纸'}样式`,
        alreadyStyle: (style) => `已经是 ${style} 样式`,
        noEditing: '没有正在编辑的贴图',
        positionConfirmed: '位置已确认',
        editCancelled: '已取消编辑',
        useLibraryEdit: '请使用贴图库的"编辑位置"功能',
        formatNotSupported: '格式不正确，只支持 PNG、WebP、JPG 格式',
        removedFromPage: '已从页面移除',
        pasteSuccess: '粘贴成功',
    },

    // ----- 通知 -----
    notification: {
        visibilityChanged: (visible) => `文章已${visible ? '可见' : '不可见'}`,
        visibilityChangedLocal: (visible) => `文章已${visible ? '可见' : '不可见'}（本地模拟）`,
        visibilityAdminOnly: '需要管理员权限',
        visibilityMadeInvisible: '该文章已被管理员设置为不可见，点击确定关闭当前阅读窗口。',
        loginSuccess: '欢迎管理员登录',
        loginFailed: '用户名或密码错误',
        logoutSuccess: '已退出管理员模式',
        decoUploadSuccess: (name) => `贴图 "${name}" 上传成功`,
        decoDuplicateSuccess: (name) => `已复制贴图 "${name}"`,
        decoDeleteConfirm: '确定要从贴图库中删除该贴图吗？',
        decoDeleteSuccess: '已删除',
        decoStyleSwitched: (style) => `已切换为${style}样式`,
        minimized: '已最小化到左下角',
        paletteSaved: '色卡已保存',
        paletteDeleted: '色卡已删除',
        paletteApplied: (name) => `已应用色卡：${name}`,
        paletteDeleteConfirm: '确定删除该色卡吗？',
        bgColorApplied: '背景颜色已应用',
        bgColorReset: '背景颜色已重置',
        gradientApplied: '渐变背景已应用',
        solidApplied: '纯色背景已应用',
        textureApplied: (size) => `纹理已应用（WebP格式，${size}KB）`,
        textureRemoved: '纹理已移除',
        textureUploadFirst: '请先上传纹理图片',
        watermarkApplied: '水印设置已应用',
        moduleNotLoaded: '模块未加载',
        operationFailed: '操作失败，请稍后重试',
        operationSuccess: '操作成功',
        articleSaved: '文章已保存',
        articleDeleted: '文章已删除',
        articleCreated: (title) => `文章 "${title}" 已创建`,
        articleRenameSuccess: '已重命名',
        articleRenameFailed: '重命名失败',
        articleDeleteFailed: '删除失败',
        articleSaveFailed: '保存失败',
        loginRequired: '请登录管理员账号',
        articleDeleteConfirm: '确定要删除这篇文章吗？此操作不可撤销！',
        refreshSuccess: '列表已刷新',
        draftSaved: '草稿已保存',
        draftSaveFailed: '草稿保存失败',
        draftDeleted: '草稿已删除',
        draftRestored: '已恢复草稿版本',
    },

    // ----- 文章编辑器 -----
    editor: {
        pageTitle: '文章编辑器 - REVACHOL',
        toolbarTitle: '✎ 文章编辑器',
        saveDraft: '保存草稿',
        publish: '发布',
        cancel: '取消',
        close: '关闭',
        sidebarTitle: '📂 目录',
        sidebarCollapse: '◀',
        sidebarExpand: '☰',
        collapseSidebar: '收起目录',
        expandSidebar: '展开目录',
        historyLabel: '历史',
        hideHistory: '隐藏历史',
        emptyState: '📝<p>点击左侧目录中的文章开始编辑</p><p style="font-size:12px;color:#7a6a58;margin-top:10px;">支持修改标题和正文内容</p>',
        titleLabel: '📌 文章标题',
        contentLabel: '📄 正文内容',
        titlePlaceholder: '输入标题...',
        contentPlaceholder: '在此输入文章内容...',
        saveSuccess: '草稿已保存',
        publishSuccess: '发布成功',
        saveFailed: '草稿保存失败: ',
        publishFailed: '发布失败: ',
        titleRequired: '标题不能为空',
        noArticleSelected: '请先选择一篇文章',
        articleNotFound: '文章不存在',
        shortcutSave: 'Ctrl+S 保存草稿',
        shortcutCancel: 'Esc 取消编辑',
    },

    // ----- 历史记录 -----
    history: {
        empty: '暂无草稿历史',
        loadError: '加载失败',
        previewTitle: '📄 草稿预览',
        previewClose: '关闭',
        previewBtn: '查看',
        restoreBtn: '恢复',
        deleteBtn: '删除',
        savedAtPrefix: '保存于',
        emptyContent: '（空内容）',
        restoreConfirm: (time) => `确定要将文章恢复为 ${time} 的草稿版本吗？`,
        deleteConfirm: (time) => `确定要删除 ${time} 的草稿吗？`,
        deleteSuccess: '草稿已删除',
        deleteFailed: '删除失败: ',
        restoreSuccess: '已恢复草稿版本',
        restoreFailed: '恢复失败: ',
        deleteError: '草稿数据异常，无法删除',
    },

    // ----- 首页首屏说明 -----
    hero: {
        title: '网站使用说明',
        description: `
            <p><strong>目录说明：</strong>点击左侧 📜 图标展开目录，双击文件夹展开/收起，单击文章跳转。</p>
            <p><strong>文件夹跳转：</strong>单击文件夹跳转到该文件夹第一篇文章。</p>
            <p><strong>文章跳转：</strong>单击文章跳转到对应卡片，双击卡片查看详情。</p>
            <p><strong>访客支持：</strong>浏览所有公开文章，使用搜索框搜索角色，无需登录即可阅读。</p>
        `
    },

    // ----- 其他（裁剪、版权等）-----
    crop: {
        title: '✂️ 裁剪头像',
        previewLabel: '预览',
        cancel: '✗ 取消',
        confirm: '✓ 确认',
    },

    copyright: '© {siteTitle} · {siteSubtitle} · 内容受版权保护 · 未经授权不得截图、复制或传播',

    // ----- 配置 -----
    config: {
        adminUsername: 'admin',
        adminPassword: 'admin123',
        defaultWatermarkText: 'REVACHOL',
        defaultBgColor: '#1a1612',
        defaultTextureOpacity: 0.12,
        defaultWatermarkOpacity: 0.15,
    },
};